### ISSUE TITLE
Parameters not updating on BatteryElectroChem

### ISSUE THREAD

**Issue by lucabig** [nasa/prog_models#94] opened 2021-08-05 10:01 UTC
Hi all,

when I try to manually update a parameter of the BatteryElectroChem model, the other parameters are not updated accordingly.
This happens for example when I change "qMobile". I would expect such a change to affect other parameters, but this doesn't happen. 
Thanks in advance,

Luca

**Comment by teubert** [comment] 2021-08-05 21:06
Hi @lucabig,

I'm sorry for your trouble. You're right that other parameters should be changed as you change qMobile. Can you tell me what version of prog_models you're using?

**Comment by lucabig** [comment] 2021-08-06 08:24
Hi @teubert ,

thanks for your quick reply!
I'm using version 1.0.1

**Comment by teubert** [comment] 2021-08-10 18:50
Thank you @lucabig, 

I was able to reproduce what you describe, and I think it was related to a bug in the way we handle derived parameters in versions 1.0.*. This should be fixed in the v1.1 release scheduled for Friday. If you want to test it out before that release you can checkout the dev branch and use the following command to install (for the repository directory):
   `pip install -e .` 

Alternatively you can wait for Friday's release.

**Comment by teubert** [comment] 2021-08-11 18:57
@lucabig : I opened a branch for the release (`release/v1.1`) Could you check and make sure that fixes your issue?

**Comment by lucabig** [comment] 2021-08-23 08:23
Dear @teubert , a new issue seems to have occurred but I might be wrong. If you try to simulate trajectories with different values of R0, nothing changes.  Am I doing something wrong?

**Comment by teubert** [comment] 2022-01-12 15:24
@lucabig was using the model BatteryElectroChem which is an alias for BatteryElectroChemEODEOL. He was then varying Ro, and was surprised (understandably) when the resulting behavior didn't change as Ro changed. 

The degradation modeling in BatteryElectroChemEODEOL overrides the parameter Ro, since Ro changes as the system ages. Using the EOD-only model BatteryElectroChemEOD yield the resulting behavior.

Suggestion: Use the derived parameters to issue a warning when Ro changes.

**Closed** 2022-01-20 18:07 UTC
Labels: bug
